"""保存済み全14件の対応測定を集計。目的の未証明を成功へ置換しない。"""
import collections,json,statistics,hashlib,csv
from pathlib import Path
from old_new_campaign_r2 import ROOT,REPO,TARGET
from correspondence_diagnostics_r1 import delivery,storage
BASE=ROOT.parent
OUT=TARGET/'results'
def read(p):return json.loads(p.read_text())
def stats(v):return {'sum':sum(v),'mean':statistics.mean(v),'median':statistics.median(v),'maximum':max(v)}
def main():
 rows=[];settings=[];sources={};diagnostics={}
 for reason in ['low','medium','high']:
  for side in ['dedicated','old']:
   root=BASE/f'standard14-dedicated-{reason}-n2-20261004-r1' if side=='dedicated' else ROOT/reason
   p=root/('final-result-r1.json' if side=='dedicated' else 'final-result-r2.json');r=read(p);sources[str(p)]=hashlib.sha256(p.read_bytes()).hexdigest()
   for row in r['cases']:
    item={k:row[k] for k in ['case_id','iteration','quality_score','behavior','total_tokens','elapsed_seconds','session_count','cached_input_tokens','raw_evidence_directory']};item.update(side=side,reasoning_effort=reason);item['retained_run_storage']=storage(Path(row['raw_evidence_directory']))
    start=read(Path(row['raw_evidence_directory'])/'start.json');item['initial_visible_file_bytes']=sum(v.get('bytes',0) for v in start['manifest'].values() if v.get('type')=='file');item['initial_visible_file_count']=sum(v.get('type')=='file' for v in start['manifest'].values());
    d=delivery(Path(row['raw_evidence_directory']));item.update(read_output_bytes=d['serialized_tool_output_utf8_bytes'],truncated_output_count=d['truncation_marked_outputs'],exact_repeated_output_count=d['exact_repeated_output_count']);rows.append(item);diagnostics[item['raw_evidence_directory']]=d
   ss=[x for x in rows if x['side']==side and x['reasoning_effort']==reason]
   settings.append({'side':side,'reasoning_effort':reason,'n':len(ss),'score_counts':dict(collections.Counter(str(x['quality_score']) for x in ss)),'tokens':stats([x['total_tokens'] for x in ss]),'cli_seconds':stats([x['elapsed_seconds'] for x in ss]),'campaign_wall_seconds':r['measurement_campaign_wall_seconds'],'initial_visible_file_bytes':stats([x['initial_visible_file_bytes'] for x in ss]),'initial_visible_file_count':stats([x['initial_visible_file_count'] for x in ss]),'delivery_bytes':sum(x['read_output_bytes'] for x in ss),'storage':storage(root),'per_iteration':{str(i):{'tokens':sum(x['total_tokens'] for x in ss if x['iteration']==i),'cli_seconds':sum(x['elapsed_seconds'] for x in ss if x['iteration']==i)} for i in [1,2]},'by_behavior':{b:{'n':len([x for x in ss if x['behavior']==b]),'tokens':stats([x['total_tokens'] for x in ss if x['behavior']==b]),'cli_seconds':stats([x['elapsed_seconds'] for x in ss if x['behavior']==b])} for b in sorted({x['behavior'] for x in ss})},'per_case':{sd:{'scores':[x['quality_score'] for x in ss if x['case_id']==sd],'behaviors':[x['behavior'] for x in ss if x['case_id']==sd],'tokens':stats([x['total_tokens'] for x in ss if x['case_id']==sd]),'cli_seconds':stats([x['elapsed_seconds'] for x in ss if x['case_id']==sd]),'retained_run_logical_bytes':stats([x['retained_run_storage']['retained_logical_bytes'] for x in ss if x['case_id']==sd]),'initial_visible_file_bytes':stats([x['initial_visible_file_bytes'] for x in ss if x['case_id']==sd]),'delivered_output_bytes':stats([x['read_output_bytes'] for x in ss if x['case_id']==sd])} for sd in sorted({x['case_id'] for x in ss})}})
 extra=read(ROOT.parent/'standard14-old-new-paired-n2-20261004-r1/low/diagnostic-consumption-r1.json')
 result={'preflight_incomplete_consumption':{k:extra[k] for k in ['model_runs','score_counts','all_agent_total_tokens','elapsed_seconds_sum']},'historical_failure_correspondence':read(TARGET/'registrations/stage5-historical-failure-correspondence-r1.json'),'schema_version':'standard14-stage5-correspondence-comparison/r1','measurement_complete':True,'substitution_certified':False,'task_objective_completed':False,'case_count':14,'criterion_count':42,'paired_measurements':168,'preparation_failures_without_model_slots':1,'additional_preflight_incomplete_diagnostic_runs':28,'new_dedicated_low_reissued':False,'sources':sources,'settings':settings,'rows':rows,'status':{'requirement_material_mapping':'stage3_accepted_14_of_14','normal_partial_forbidden_scoring':'stage3_accepted_42_criteria','empirical_difficulty_equivalence':'unproved','historical_raw_failure_replay_equivalence':'unproved','token_reduction':'observed_setting_specific','same_cli_boundary_time':'observed_setting_specific','all_required_storage_reduction':'unproved','peak_and_apfs_exclusive':'unobserved','internal_cli_intervals':'unobserved'},'limits':['N2各設定。別インスタンスを同じatomic poolへ登録しない。','比較で変えるのは宣言された素材・TaskSpecのseed値・採点実装接続。意味同等性は独立した未証明条件。','配送tool出力のbyteは読了やtokenを表さない。要求中のpath字句はtest/diffも含む。','保持量は終了後の現物。APFS共有物理量、ピーク、削除前量を推計しない。','旧Low第1版は開始記録の互換照合漏れ28件。第2版の実測と混ぜず消費を保持する。']}
 (OUT/'standard14-old-new-comparison-r1.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n')
 (ROOT/'delivery-diagnostics-all-r1.json').write_text(json.dumps(diagnostics,ensure_ascii=False,indent=2)+'\n')
 with (OUT/'standard14-old-new-runs-r1.tsv').open('w') as f:
  fields=[k for k in rows[0] if k!='retained_run_storage'];w=csv.DictWriter(f,fieldnames=fields,delimiter='\t',extrasaction='ignore');w.writeheader();w.writerows(rows)
 lines=['# STD14専用評価の旧新比較結果 第1版','','全14件のLow・Medium・High各N2を旧素材と専用素材で保存した。測定は完了したが、難しさと保存済み失敗の全件再演、ストレージの全要求が未証明のため、低コストな同等代替としては認定しない。目的全体は未完了である。','','| 設定 | 素材 | 有効件数 | 点数分布 | 全担当トークン | CLI時間合計（秒） | 実行群時間（秒） | 配送出力（byte） | 保持論理量（byte） |','|---|---|---:|---|---:|---:|---:|---:|---:|']
 for s in settings:lines.append(f"| {s['reasoning_effort']} | {'専用' if s['side']=='dedicated' else '旧'} | {s['n']} | {s['score_counts']} | {s['tokens']['sum']:,} | {s['cli_seconds']['sum']:.3f} | {s['campaign_wall_seconds']:.3f} | {s['delivery_bytes']:,} | {s['storage']['retained_logical_bytes']:,} |")
 lines+=['','CLI時間は同じ実行器の起動から終了までの単調時計である。実行群時間は24件＋4件と、その間の採点・準備待ちを含む。内部区間はCLI0.159.0の保存証拠から観測できない。ピークとAPFS専有物理量も未観測であり、推計で補わない。','','| 設定 | トークン削減率 | CLI時間合計削減率 | 配送出力削減率 |','|---|---:|---:|---:|']
 for reason in ['low','medium','high']:
  n=next(s for s in settings if s['reasoning_effort']==reason and s['side']=='dedicated');o=next(s for s in settings if s['reasoning_effort']==reason and s['side']=='old');lines.append(f"| {reason} | {(1-n['tokens']['sum']/o['tokens']['sum'])*100:.2f}% | {(1-n['cli_seconds']['sum']/o['cli_seconds']['sum'])*100:.2f}% | {(1-n['delivery_bytes']/o['delivery_bytes'])*100:.2f}% |")
 lines+=['','これらは今回の実測群の差である。失敗や停止を成功に変換せず含めた集計であり、難しさの同等性や将来の削減を保証しない。','','全42条件の素材対応と正常・部分・禁止動作の区分は、工程3第4版の受入を保持した。今回の旧側は元の契約・source・終了応答・実操作と検証成功を独立判定して同じ点数区分へ接続した。専用側の別API用検査を旧素材へ適用していない。歴史の品質点は書き換えていない。','','| ケース | 必要な成果 | Low（旧／専用） | Medium（旧／専用） | High（旧／専用） |','|---|---|---|---|---|']
 verdict=read(TARGET/'registrations/stage3-verdict-r4.json')
 for c in verdict['cases']:
  vals=[]
  for reason in ['low','medium','high']:
   vals.append(' / '.join(','.join(str(x['quality_score']) for x in rows if x['reasoning_effort']==reason and x['side']==side and x['case_id']==c['case_id']) for side in ['old','dedicated']))
  lines.append('| '+ ' | '.join([c['case_id'],c['required_result']]+vals)+' |')
 lines+=['','ケース別、反復別、動作別の全値と平均・中央値・最大は [集計JSON](../evaluations/targets/standard14-dedicated-control/results/standard14-old-new-comparison-r1.json) に、各実行の値は [TSV](../evaluations/targets/standard14-dedicated-control/results/standard14-old-new-runs-r1.tsv) に保存した。各行は非公開の証拠保存先に結ぶ。配送対象の字句・重複・切詰め記録は外部の `delivery-diagnostics-all-r1.json` に保存した。','','保存済みのA01以外の失敗10件中、7件は元監査の欠落predicateを専用採点へ接続し、全成功として誤受理しないことを確認した。残る3件と、生のdiff・終了応答・実操作を使う全件再演は未完了である。これは過去の点数の再採点でもモデル再実行でもない。証跡は `registrations/stage5-historical-failure-correspondence-r1.json` に保存した。','','旧素材は全repositoryとGit履歴を保持するが、専用素材は必要経路の投影である。旧側のauthority用commitを予定外変更と解釈した停止と、入口レビューの開始記録探索は、同じ42条件でも判断負荷が等しい証明にならない。全体の得点が高いことやA01だけの失敗一致で全14件へ一般化しない。素材関係の欠落が立証されていないため、今回の比較差を根拠に固定素材・TaskSpec・採点を変更していない。','','保持量はGit objects、その他Git情報、可視file、依存とbuild、cache、Layer 1、証拠の区分をJSONへ記録した。旧第2版が参照する第1版の固定素材と共通Python・Node原本はsymlink経由で数えないため、表の保持量だけで総ストレージ削減を認定しない。run単位と準備原本の関係、共有物理量とピークは別の未証明条件として残る。','','旧Low第1版の28件は開始記録にだけ素材構築情報が含まれる照合漏れがあった。発行前確認の不備として記録し、生の証拠と低得点と消費を保持した。旧Medium・High第1版は発行せず、同じ開始記録形式へそろえた第2版で旧84件を実行した。専用Lowは再発行していない。今回の追加発行は専用Medium・High56件、旧112件であり、自動再試行、N5・N20延長はない。','','元の工程1・工程3固定成果、旧結果、別pool、外部実行器を維持した。commit・push・PR・mergeは行っていない。作業チャットの実設定はgpt-6.1-sol／lowを保存sessionから別の証跡に固定した。result内の作業model未推定という既存値を、測定modelの設定と混同しない。']
 (REPO/'docs/standard14-dedicated-stage5-final-report-r1.md').write_text('\n'.join(lines)+'\n')
 print(json.dumps([{k:s[k] for k in ['side','reasoning_effort','score_counts','tokens','cli_seconds','delivery_bytes']} for s in settings],ensure_ascii=False))
if __name__=='__main__':main()
